version: "2"
linters:
  default: all
  disable:
    - depguard
    - forbidigo
    - varnamelen
    - wsl
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
