version: "2"
linters:
  default: all
  disable:
    - depguard
    - forbidigo
    - paralleltest
    - varnamelen
    - wsl
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
