version: "2"
linters:
  default: all
  disable:
    - depguard
    - forbidigo
    - paralleltest
    - varnamelen
    - wsl
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
