name: Linting
on:
  push:

jobs:
  lint:
    name: Prettier & markdown linting
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [23]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Prettier lint
        run: pnpm prettier:lint .
      - name: markdown lint
        run: pnpm markdown:lint .
